using System;
namespace GECF.Models
{
    public class NonGECFCountriesDataResponse
    {
        public List<NDatum> data { get; set; }
        public int status { get; set; }
    }


    public class NDatum
    {
        public string country { get; set; }
        public string country_code { get; set; }
        public string country_type { get; set; }
        public string type { get; set; }
        public string type_code { get; set; }
        public List<int> color { get; set; }
        public string year1 { get; set; }
        public string month1 { get; set; }
        public string value1 { get; set; }
        public string year2 { get; set; }
        public string month2 { get; set; }
        public string value2 { get; set; }
        public string year3 { get; set; }
        public string month3 { get; set; }
        public string value3 { get; set; }
        public string year4 { get; set; }
        public string month4 { get; set; }
        public string value4 { get; set; }
        public string year5 { get; set; }
        public string month5 { get; set; }
        public string value5 { get; set; }
        public string year6 { get; set; }
        public string month6 { get; set; }
        public string value6 { get; set; }
        public string year7 { get; set; }
        public string month7 { get; set; }
        public string value7 { get; set; }
        public string year8 { get; set; }
        public string month8 { get; set; }
        public string value8 { get; set; }
        public string year9 { get; set; }
        public string month9 { get; set; }
        public string value9 { get; set; }
        public string year10 { get; set; }
        public string month10 { get; set; }
        public string value10 { get; set; }
        public string year11 { get; set; }
        public string month11 { get; set; }
        public string value11 { get; set; }
        public string year12 { get; set; }
        public string month12 { get; set; }
        public string value12 { get; set; }
        public string year13 { get; set; }
        public string month13 { get; set; }
        public string value13 { get; set; }
        public string year14 { get; set; }
        public string month14 { get; set; }
        public string value14 { get; set; }
        public string year15 { get; set; }
        public string month15 { get; set; }
        public string value15 { get; set; }
        public string year16 { get; set; }
        public string month16 { get; set; }
        public string value16 { get; set; }
        public string year17 { get; set; }
        public string month17 { get; set; }
        public string value17 { get; set; }
        public string year18 { get; set; }
        public string month18 { get; set; }
        public string value18 { get; set; }
        public string year19 { get; set; }
        public string month19 { get; set; }
        public string value19 { get; set; }
        public string year20 { get; set; }
        public string month20 { get; set; }
        public string value20 { get; set; }
        public string year21 { get; set; }
        public string month21 { get; set; }
        public string value21 { get; set; }
        public string year22 { get; set; }
        public string month22 { get; set; }
        public string value22 { get; set; }
        public string year23 { get; set; }
        public string month23 { get; set; }
        public string value23 { get; set; }
        public string year24 { get; set; }
        public string month24 { get; set; }
        public string value24 { get; set; }
        public string year25 { get; set; }
        public string month25 { get; set; }
        public string value25 { get; set; }
        public string year26 { get; set; }
        public string month26 { get; set; }
        public string value26 { get; set; }
        public string year27 { get; set; }
        public string month27 { get; set; }
        public string value27 { get; set; }
        public string year28 { get; set; }
        public string month28 { get; set; }
        public string value28 { get; set; }
        public string year29 { get; set; }
        public string month29 { get; set; }
        public string value29 { get; set; }
        public string year30 { get; set; }
        public string month30 { get; set; }
        public string value30 { get; set; }
        public string year31 { get; set; }
        public string month31 { get; set; }
        public string value31 { get; set; }
        public string year32 { get; set; }
        public string month32 { get; set; }
        public string value32 { get; set; }
        public string year33 { get; set; }
        public string month33 { get; set; }
        public string value33 { get; set; }
        public string year34 { get; set; }
        public string month34 { get; set; }
        public string value34 { get; set; }
        public string year35 { get; set; }
        public string month35 { get; set; }
        public string value35 { get; set; }
        public string year36 { get; set; }
        public string month36 { get; set; }
        public string value36 { get; set; }
        public string year37 { get; set; }
        public string month37 { get; set; }
        public string value37 { get; set; }
        public string year38 { get; set; }
        public string month38 { get; set; }
        public string value38 { get; set; }
        public string year39 { get; set; }
        public string month39 { get; set; }
        public string value39 { get; set; }
        public string year40 { get; set; }
        public string month40 { get; set; }
        public string value40 { get; set; }
        public string year41 { get; set; }
        public string month41 { get; set; }
        public string value41 { get; set; }
        public string year42 { get; set; }
        public string month42 { get; set; }
        public string value42 { get; set; }
        public string year43 { get; set; }
        public string month43 { get; set; }
        public string value43 { get; set; }
        public string year44 { get; set; }
        public string month44 { get; set; }
        public string value44 { get; set; }
        public string year45 { get; set; }
        public string month45 { get; set; }
        public string value45 { get; set; }
        public string year46 { get; set; }
        public string month46 { get; set; }
        public string value46 { get; set; }
        public string year47 { get; set; }
        public string month47 { get; set; }
        public string value47 { get; set; }
        public string year48 { get; set; }
        public string month48 { get; set; }
        public string value48 { get; set; }
        public string year49 { get; set; }
        public string month49 { get; set; }
        public string value49 { get; set; }
        public string year50 { get; set; }
        public string month50 { get; set; }
        public string value50 { get; set; }
        public string year51 { get; set; }
        public string month51 { get; set; }
        public string value51 { get; set; }
        public string year52 { get; set; }
        public string month52 { get; set; }
        public string value52 { get; set; }
        public string year53 { get; set; }
        public string month53 { get; set; }
        public string value53 { get; set; }
        public string year54 { get; set; }
        public string month54 { get; set; }
        public string value54 { get; set; }
        public string year55 { get; set; }
        public string month55 { get; set; }
        public string value55 { get; set; }
        public string year56 { get; set; }
        public string month56 { get; set; }
        public string value56 { get; set; }
        public string year57 { get; set; }
        public string month57 { get; set; }
        public string value57 { get; set; }
        public string year58 { get; set; }
        public string month58 { get; set; }
        public string value58 { get; set; }
        public string year59 { get; set; }
        public string month59 { get; set; }
        public string value59 { get; set; }
        public string year60 { get; set; }
        public string month60 { get; set; }
        public string value60 { get; set; }
        public string year61 { get; set; }
        public string month61 { get; set; }
        public string value61 { get; set; }
        public string year62 { get; set; }
        public string month62 { get; set; }
        public string value62 { get; set; }
        public string year63 { get; set; }
        public string month63 { get; set; }
        public string value63 { get; set; }
        public string year64 { get; set; }
        public string month64 { get; set; }
        public string value64 { get; set; }
        public string year65 { get; set; }
        public string month65 { get; set; }
        public string value65 { get; set; }
        public string year66 { get; set; }
        public string month66 { get; set; }
        public string value66 { get; set; }
        public string year67 { get; set; }
        public string month67 { get; set; }
        public string value67 { get; set; }
        public string year68 { get; set; }
        public string month68 { get; set; }
        public string value68 { get; set; }
        public string year69 { get; set; }
        public string month69 { get; set; }
        public string value69 { get; set; }
        public string year70 { get; set; }
        public string month70 { get; set; }
        public string value70 { get; set; }
        public string year71 { get; set; }
        public string month71 { get; set; }
        public string value71 { get; set; }
        public string year72 { get; set; }
        public string month72 { get; set; }
        public string value72 { get; set; }
        public string year73 { get; set; }
        public string month73 { get; set; }
        public string value73 { get; set; }
        public string year74 { get; set; }
        public string month74 { get; set; }
        public string value74 { get; set; }
        public string year75 { get; set; }
        public string month75 { get; set; }
        public string value75 { get; set; }
        public string year76 { get; set; }
        public string month76 { get; set; }
        public string value76 { get; set; }
        public string year77 { get; set; }
        public string month77 { get; set; }
        public string value77 { get; set; }
        public string year78 { get; set; }
        public string month78 { get; set; }
        public string value78 { get; set; }
        public string year79 { get; set; }
        public string month79 { get; set; }
        public string value79 { get; set; }
        public string year80 { get; set; }
        public string month80 { get; set; }
        public string value80 { get; set; }
        public string year81 { get; set; }
        public string month81 { get; set; }
        public string value81 { get; set; }
        public string year82 { get; set; }
        public string month82 { get; set; }
        public string value82 { get; set; }
        public string year83 { get; set; }
        public string month83 { get; set; }
        public string value83 { get; set; }
        public string year84 { get; set; }
        public string month84 { get; set; }
        public string value84 { get; set; }
        public string year85 { get; set; }
        public string month85 { get; set; }
        public string value85 { get; set; }
        public string year86 { get; set; }
        public string month86 { get; set; }
        public string value86 { get; set; }
        public string year87 { get; set; }
        public string month87 { get; set; }
        public string value87 { get; set; }
        public string year88 { get; set; }
        public string month88 { get; set; }
        public string value88 { get; set; }
        public string year89 { get; set; }
        public string month89 { get; set; }
        public string value89 { get; set; }
        public string year90 { get; set; }
        public string month90 { get; set; }
        public string value90 { get; set; }
        public string year91 { get; set; }
        public string month91 { get; set; }
        public string value91 { get; set; }
        public string year92 { get; set; }
        public string month92 { get; set; }
        public string value92 { get; set; }
        public string year93 { get; set; }
        public string month93 { get; set; }
        public string value93 { get; set; }
        public string year94 { get; set; }
        public string month94 { get; set; }
        public string value94 { get; set; }
        public string year95 { get; set; }
        public string month95 { get; set; }
        public string value95 { get; set; }
        public string year96 { get; set; }
        public string month96 { get; set; }
        public string value96 { get; set; }
        public string year97 { get; set; }
        public string month97 { get; set; }
        public string value97 { get; set; }
        public string year98 { get; set; }
        public string month98 { get; set; }
        public string value98 { get; set; }
        public string year99 { get; set; }
        public string month99 { get; set; }
        public string value99 { get; set; }
        public string year100 { get; set; }
        public string month100 { get; set; }
        public string value100 { get; set; }
        public string year101 { get; set; }
        public string month101 { get; set; }
        public string value101 { get; set; }
        public string year102 { get; set; }
        public string month102 { get; set; }
        public string value102 { get; set; }
        public string year103 { get; set; }
        public string month103 { get; set; }
        public string value103 { get; set; }
        public string year104 { get; set; }
        public string month104 { get; set; }
        public string value104 { get; set; }
        public string year105 { get; set; }
        public string month105 { get; set; }
        public string value105 { get; set; }
        public string year106 { get; set; }
        public string month106 { get; set; }
        public string value106 { get; set; }
        public string year107 { get; set; }
        public string month107 { get; set; }
        public string value107 { get; set; }
        public string year108 { get; set; }
        public string month108 { get; set; }
        public string value108 { get; set; }
        public string year109 { get; set; }
        public string month109 { get; set; }
        public string value109 { get; set; }
        public string year110 { get; set; }
        public string month110 { get; set; }
        public string value110 { get; set; }
        public string year111 { get; set; }
        public string month111 { get; set; }
        public string value111 { get; set; }
        public string year112 { get; set; }
        public string month112 { get; set; }
        public string value112 { get; set; }
        public string year113 { get; set; }
        public string month113 { get; set; }
        public string value113 { get; set; }
        public string year114 { get; set; }
        public string month114 { get; set; }
        public string value114 { get; set; }
        public string year115 { get; set; }
        public string month115 { get; set; }
        public string value115 { get; set; }
        public string year116 { get; set; }
        public string month116 { get; set; }
        public string value116 { get; set; }
        public string year117 { get; set; }
        public string month117 { get; set; }
        public string value117 { get; set; }
        public string year118 { get; set; }
        public string month118 { get; set; }
        public string value118 { get; set; }
        public string year119 { get; set; }
        public string month119 { get; set; }
        public string value119 { get; set; }
        public string year120 { get; set; }
        public string month120 { get; set; }
        public string value120 { get; set; }
        public string year121 { get; set; }
        public string month121 { get; set; }
        public string value121 { get; set; }
        public string year122 { get; set; }
        public string month122 { get; set; }
        public string value122 { get; set; }
        public string year123 { get; set; }
        public string month123 { get; set; }
        public string value123 { get; set; }
        public string year124 { get; set; }
        public string month124 { get; set; }
        public string value124 { get; set; }
        public string year125 { get; set; }
        public string month125 { get; set; }
        public string value125 { get; set; }
        public string year126 { get; set; }
        public string month126 { get; set; }
        public string value126 { get; set; }
        public string year127 { get; set; }
        public string month127 { get; set; }
        public string value127 { get; set; }
        public string year128 { get; set; }
        public string month128 { get; set; }
        public string value128 { get; set; }
        public string year129 { get; set; }
        public string month129 { get; set; }
        public string value129 { get; set; }
    }
}

