//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GECF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GECF.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string login_hint
        {
            get
            {
                return ResourceManager.GetString("login_hint", resourceCulture);
            }
        }

        internal static string password_hint
        {
            get
            {
                return ResourceManager.GetString("password_hint", resourceCulture);
            }
        }

        internal static string logo_text
        {
            get
            {
                return ResourceManager.GetString("logo_text", resourceCulture);
            }
        }

        internal static string checknetwork
        {
            get
            {
                return ResourceManager.GetString("checknetwork", resourceCulture);
            }
        }

        internal static string error
        {
            get
            {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }

        internal static string ok
        {
            get
            {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        internal static string exception
        {
            get
            {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }

        internal static string reset_password
        {
            get
            {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }

        internal static string remember_password
        {
            get
            {
                return ResourceManager.GetString("remember_password", resourceCulture);
            }
        }

        internal static string login123
        {
            get
            {
                return ResourceManager.GetString("login123", resourceCulture);
            }
        }

        internal static string login
        {
            get
            {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }

        internal static string GECF
        {
            get
            {
                return ResourceManager.GetString("GECF", resourceCulture);
            }
        }

        internal static string home_news
        {
            get
            {
                return ResourceManager.GetString("home_news", resourceCulture);
            }
        }

        internal static string home_prices
        {
            get
            {
                return ResourceManager.GetString("home_prices", resourceCulture);
            }
        }

        internal static string home_statistics
        {
            get
            {
                return ResourceManager.GetString("home_statistics", resourceCulture);
            }
        }

        internal static string home_research
        {
            get
            {
                return ResourceManager.GetString("home_research", resourceCulture);
            }
        }

        internal static string date
        {
            get
            {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }

        internal static string oil_Party
        {
            get
            {
                return ResourceManager.GetString("oil_Party", resourceCulture);
            }
        }

        internal static string nea
        {
            get
            {
                return ResourceManager.GetString("nea", resourceCulture);
            }
        }

        internal static string nbp
        {
            get
            {
                return ResourceManager.GetString("nbp", resourceCulture);
            }
        }

        internal static string swe
        {
            get
            {
                return ResourceManager.GetString("swe", resourceCulture);
            }
        }

        internal static string hh
        {
            get
            {
                return ResourceManager.GetString("hh", resourceCulture);
            }
        }

        internal static string Japan_lt
        {
            get
            {
                return ResourceManager.GetString("Japan_lt", resourceCulture);
            }
        }

        internal static string opec
        {
            get
            {
                return ResourceManager.GetString("opec", resourceCulture);
            }
        }

        internal static string brent
        {
            get
            {
                return ResourceManager.GetString("brent", resourceCulture);
            }
        }

        /* RJMU Jun 2022 New Prices 2022 */

        internal static string oilindex1
        {
            get
            {
                return ResourceManager.GetString("oilindex1", resourceCulture);
            }
        }

        internal static string oilindex2
        {
            get
            {
                return ResourceManager.GetString("oilindex2", resourceCulture);
            }
        }

        internal static string ttf
        {
            get
            {
                return ResourceManager.GetString("ttf", resourceCulture);
            }
        }

        internal static string jkmlsf
        {
            get
            {
                return ResourceManager.GetString("jkmlsf", resourceCulture);
            }
        }

        internal static string aeco
        {
            get
            {
                return ResourceManager.GetString("aeco", resourceCulture);
            }
        }



        internal static string help
        {
            get
            {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }

        internal static string please_send_feedback
        {
            get
            {
                return ResourceManager.GetString("please_send_feedback", resourceCulture);
            }
        }

        internal static string it_helpdesk
        {
            get
            {
                return ResourceManager.GetString("it_helpdesk", resourceCulture);
            }
        }

        internal static string contact
        {
            get
            {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }

        internal static string contact_us_address
        {
            get
            {
                return ResourceManager.GetString("contact_us_address", resourceCulture);
            }
        }

        internal static string telephone
        {
            get
            {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }

        internal static string fax
        {
            get
            {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }

        internal static string about_us
        {
            get
            {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }

        internal static string about_us_text
        {
            get
            {
                return ResourceManager.GetString("about_us_text", resourceCulture);
            }
        }

        internal static string news
        {
            get
            {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }

        internal static string statistics
        {
            get
            {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }

        internal static string research
        {
            get
            {
                return ResourceManager.GetString("research", resourceCulture);
            }
        }

        internal static string priceNews
        {
            get
            {
                return ResourceManager.GetString("priceNews", resourceCulture);
            }
        }

        internal static string supply_DemandNews
        {
            get
            {
                return ResourceManager.GetString("supply_DemandNews", resourceCulture);
            }
        }

        internal static string transportationNews
        {
            get
            {
                return ResourceManager.GetString("transportationNews", resourceCulture);
            }
        }

        internal static string policyNews
        {
            get
            {
                return ResourceManager.GetString("policyNews", resourceCulture);
            }
        }


        internal static string economicsNews
        {
            get
            {
                return ResourceManager.GetString("economicsNews", resourceCulture);
            }
        }

        internal static string technologyNews
        {
            get
            {
                return ResourceManager.GetString("technologyNews", resourceCulture);
            }
        }

        internal static string environmentNews
        {
            get
            {
                return ResourceManager.GetString("environmentNews", resourceCulture);
            }
        }

        internal static string tradeNews
        {
            get
            {
                return ResourceManager.GetString("tradeNews", resourceCulture);
            }
        }

        internal static string assesmentNews
        {
            get
            {
                return ResourceManager.GetString("assesmentNews", resourceCulture);
            }
        }

        internal static string priceCommentryNews
        {
            get
            {
                return ResourceManager.GetString("priceCommentryNews", resourceCulture);
            }
        }

        internal static string hidrogenNews
        {
            get
            {
                return ResourceManager.GetString("hydrogenNews", resourceCulture);
            }
        }



        internal static string todaysNews
        {
            get
            {
                return ResourceManager.GetString("todaysNews", resourceCulture);
            }
        }

        internal static string listNews
        {
            get
            {
                return ResourceManager.GetString("listNews", resourceCulture);
            }
        }

        internal static string settings
        {
            get
            {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        internal static string number_of_lines
        {
            get
            {
                return ResourceManager.GetString("number_of_lines", resourceCulture);
            }
        }

        internal static string version
        {
            get
            {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }

        internal static string statisticalReports
        {
            get
            {
                return ResourceManager.GetString("statisticalReports", resourceCulture);
            }
        }

        internal static string monthly
        {
            get
            {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }

        internal static string quarterly
        {
            get
            {
                return ResourceManager.GetString("quarterly", resourceCulture);
            }
        }

        internal static string annual
        {
            get
            {
                return ResourceManager.GetString("annual", resourceCulture);
            }
        }

        internal static string report_tyoe
        {
            get
            {
                return ResourceManager.GetString("report_tyoe", resourceCulture);
            }
        }

        internal static string gasMarketReports
        {
            get
            {
                return ResourceManager.GetString("gasMarketReports", resourceCulture);
            }
        }

        internal static string outlookReports
        {
            get
            {
                return ResourceManager.GetString("outlookReports", resourceCulture);
            }
        }

        internal static string member_countries
        {
            get
            {
                return ResourceManager.GetString("member_countries", resourceCulture);
            }
        }

        internal static string observer_countries
        {
            get
            {
                return ResourceManager.GetString("observer_countries", resourceCulture);
            }
        }

        internal static string nonGECF_countries
        {
            get
            {
                return ResourceManager.GetString("nonGECF_countries", resourceCulture);
            }
        }

        internal static string expert_Commentaries
        {
            get
            {
                return ResourceManager.GetString("expert_Commentaries", resourceCulture);
            }
        }

        internal static string definitions
        {
            get
            {
                return ResourceManager.GetString("definitions", resourceCulture);
            }
        }

        internal static string search
        {
            get
            {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        internal static string search_keyword
        {
            get
            {
                return ResourceManager.GetString("search_keyword", resourceCulture);
            }
        }

        internal static string region
        {
            get
            {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }

        internal static string country
        {
            get
            {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }

        internal static string category
        {
            get
            {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }

        internal static string fromDate
        {
            get
            {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }

        internal static string toDate
        {
            get
            {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }

        internal static string maxresult_count
        {
            get
            {
                return ResourceManager.GetString("maxresult_count", resourceCulture);
            }
        }
    }
}
